export const friends = [
  {
    name: 'Ram_Charam',
    accountName: 'Ram Charan',
    profileImage: require('../../assets/images/profile4.jpg'),
    posts: 56,
    followers: 6542,
    following: 43,
    follow: false,
  },
  {
    name: 'The_Tom',
    accountName: 'Tom',
    profileImage: require('../../assets/images/profile5.jpg'),
    posts: 56,
    followers: 6542,
    following: 43,
    follow: false,
  },
  {
    name: 'live_long',
    accountName: 'Live long',
    profileImage: require('../../assets/images/profile2.jpg'),
    posts: 56,
    followers: 6542,
    following: 43,
    follow: false,
  },
  {
    name: 'the_real_hero',
    accountName: 'Ram Charan',
    profileImage: require('../../assets/images/post1.jpg'),
    posts: 56,
    followers: 6542,
    following: 43,
    follow: false,
  },
  {
    name: 'the_jerry',
    accountName: 'The Jerry',
    profileImage: require('../../assets/images/post2.jpg'),
    posts: 56,
    followers: 6542,
    following: 43,
    follow: false,
  },
  {
    name: 'angry_bird',
    accountName: 'Angry Bird',
    profileImage: require('../../assets/images/post3.jpg'),
    posts: 56,
    followers: 6542,
    following: 43,
    follow: false,
  },
  {
    name: 'mr_bean',
    accountName: 'Mr Bean',
    profileImage: require('../../assets/images/post4.jpg'),
    posts: 56,
    followers: 6542,
    following: 43,
    follow: false,
  },
  {
    name: 'the_Jd',
    accountName: 'Mr JD',
    profileImage: require('../../assets/images/post5.jpg'),
    posts: 56,
    followers: 6542,
    following: 43,
    follow: false,
  },
  {
    name: '_don_',
    accountName: 'Don',
    profileImage: require('../../assets/images/post6.jpg'),
    posts: 56,
    followers: 6542,
    following: 43,
    follow: false,
  },
  {
    name: 'black_white',
    accountName: 'blackWhite',
    profileImage: require('../../assets/images/post7.jpg'),
    posts: 56,
    followers: 6542,
    following: 43,
    follow: false,
  },
  {
    name: 'iron_man',
    accountName: 'Iron Man',
    profileImage: require('../../assets/images/post8.jpg'),
    posts: 56,
    followers: 6542,
    following: 43,
    follow: false,
  },
  {
    name: 'funny_videos',
    accountName: 'Funny Video Official',
    profileImage: require('../../assets/images/post9.jpg'),
    posts: 56,
    followers: 6542,
    following: 43,
    follow: false,
  },
  {
    name: 'mr_john',
    accountName: 'Mr Jhony',
    profileImage: require('../../assets/images/post10.jpg'),
    posts: 56,
    followers: 6542,
    following: 43,
    follow: false,
  },
];
